"""add Area

Revision ID: 55f35288c731
Revises: 700e787a3a40
Create Date: 2020-07-19 00:13:43.036036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f35288c731'
down_revision = '700e787a3a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('Area', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'Area')
    # ### end Alembic commands ###
