"""Init tables

Revision ID: 700e787a3a40
Revises: 
Create Date: 2020-07-19 00:11:09.433018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700e787a3a40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=35), nullable=False),
    sa.Column('CountryCode', sa.String(length=3), nullable=False),
    sa.Column('District', sa.String(length=20), nullable=False),
    sa.Column('Population', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    # ### end Alembic commands ###
